export const message = {
  MaxDate: "$property - $constraint1",
  MinDate: "$property - $constraint1",
  IsDecimal:"$property не является допустимым десятичным числом.",
  IsBIC: "$property должен быть BIC или SWIFT кодом",
  IsBooleanString: "$property должен быть логической строкой",
  IsBoolean: "$property должен быть логическим значением",
  IsBtcAddress: "$property должен быть BTC адресом",
  IsCreditCard: "$property должен быть кредитной картой",
  IsCurrency: "$property должно быть валютой",
  IsDataURI: "$property должно быть форматом uri данных",
  IsDate: "$property должен быть экземпляром даты",
  IsFirebasePushId: "$property должен быть идентификатором Push в Firebase",
  IsHash: "$property должен быть хэшем типа $constraint1",
  IsHexColor: "$property должен быть шестнадцатеричным цветом",
  IsHexadecimal: "$property должен быть шестнадцатеричным числом",
  IsHSL: "$property должен быть HSL цветом",
  IsIdentityCard: "$property должен быть идентификационным номером карты",
  IsISSN: "$property должен быть ISSN",
  IsJSON: "$property должен быть json строкой",
  IsJWT: "$property должно быть строкой jwt",
  IsLatitude: "$property должен быть строкой широты или числом",
  IsLatLong: "$property должен быть широтой,строка долготы",
  IsLongitude: "$property должен быть строкой или числом",
  IsLowercase: "$property должен быть строкой в нижнем регистре",
  IsMacAddress: "$property должен быть MAC-адресом",
  IsMongoId: "$property должен быть идентификатором обезьяны",
  IsNegative: "$property должно быть отрицательным числом",
  IsNotEmptyObject: "$property должен быть непустым объектом",
  IsNumber: "$property должен быть числом, соответствующим указанным ограничениям",
  IsNumberString: "$property должен быть числовой строкой",
  IsMobilePhone: "$property должен быть номером телефона",
  IsPort: "$property должен быть портом",
  IsPositive: "$property должно быть положительным числом",
  IsPostalCode: "$property должен быть почтовым индексом",
  IsSemVer: "$property должен быть спецификацией для Semantic Versioning",
  IsString: "$property должен быть строкой",
  IsFQDN: "$property должен быть допустимым именем домена",
  IsEnum: "$property должен быть допустимым значением enum",
  IsDateString:"$property должен быть допустимой строкой даты ISO 8601",
  IsISO8601: "$property должен быть допустимой строкой даты ISO 8601",
  IsISO31661Alpha2: "$property должен быть допустимым ISO31661 код Alpha2",
  IsISO31661Alpha3: "$property должен быть действительным ISO31661 код Alpha3",
  IsPhoneNumber: "$property должен быть действительным номером телефона",
  IsMilitaryTime: "$property должен быть корректным представлением военного времени в формате HH:MM",
  IsArray: "$property должен быть массивом",
  IsEAN: "$property должен быть EAN (европейский номер статьи)",
  IsEmail: "$property должен быть email",
  IsEthereumAddress: "$property должен быть Ethereum адресом",
  IsIBAN: "$property должен быть IBAN",
  IsInstance: "$property должен быть экземпляром $constraint1name",
  IsInt: "$property должно быть целым числом",
  IsIP: "$property должен быть IP-адресом",
  IsISBN: "$property должен быть ISBN",
  IsISIN: "$property должен быть ISIN (идентификатор запасов/безопасности)",
  IsISRC: "$property должен быть ISRC",
  IsObject: "$property должен быть объектом",
  IsUrl: "$property должен быть URL-адресом",
  IsUUID: "$property должен быть UUID",
  IsBase32: "$property должен быть в кодировке base32",
  IsBase64: "$property должен быть в кодировке base64",
  IsDivisibleBy: "$property должен быть делим на $constraint1",
  IsEmpty: "$property должен быть пустым",
  Equals: "$property должен быть равен $constraint1",
  IsLocale: "$property должен быть локалью",
  StringLength: "$property должен быть длиннее или равен $constraint1 и меньше или равен $constraint2 символов",
  MinLength: "$property должен быть длиннее или равен $constraint1 символов",
  IsMagnetURI: "$property должно быть в формате Magnet uri",
  IsMimeType: "$property должен быть MIME-форматом",
  IsIn: "$property должен быть одним из следующих значений: $constraint1",
  IsRFC3339: "$property должен быть датой RFC 3339",
  IsRgbColor: "$property должен быть RGB цвет",
  MaxLength: "$property должен быть короче или равен $constraint1 символов",
  Length: "$property должен быть короче или равен $constraint2 символов",
  IsUppercase: "$property должен быть заглавным",
  IsOctal: "$property должно быть действительным восьмеричным числом",
  IsPassportNumber: "$property должен быть действительным номером паспорта",
  ArrayContains: "$property должен содержать $constraint1 значений",
  Contains: "$property должен содержать $constraint1 строку",
  IsVariableWidth: "$property должен содержать символы с полной шириной и полушириной",
  IsFullWidth: "$property должен содержать целую ширину символов",
  IsHalfWidth: "$property должен содержать символы с половиной ширины",
  IsSurrogatePair: "$property должен содержать любые пары суррогатных символов",
  ArrayMinSize: "$property должен содержать как минимум $constraint1 элементов",
  ArrayMaxSize: "$property должен содержать не более $constraint1 элементов",
  IsMultibyte: "$property должен содержать один или более символов в мультибайтах",
  IsAscii: "$property должен содержать только ASCII символы",
  IsAlpha: "$property должен содержать только буквы (a-zA-Z)",
  IsAlphanumeric: "$property должен содержать только буквы и цифры",
  Matches: "$property должен совпадать с регулярным выражением $constraint1",
  Max: "$property не должен быть больше чем $constraint1",
  Min: "$property должен быть не меньше чем $constraint1",
  ArrayNotEmpty:"$property не может быть пустым",
  IsNotEmpty: "$property не может быть пустым",
  NotEquals: "$property не должен быть равен $constraint1",
  IsDefined: "$property не должен быть пустым или неопределенным",
  IsNotIn: "$property не должен быть одним из следующих значений: $constraint1",
  ArrayNotContains: "$property не должен содержать $constraint1 значений",
  NotContains: "$property не должен содержать $constraint1 строку",
  IsByteLength: "длина байта $property должна совпадать с диапазоном ($constraint1, $constraint2)",
  ArrayUnique: "Все элементы $property должны быть уникальными",
  //ValidateNested: "каждое значение в ",
  //MaxDate: "максимально допустимая дата для ",
  //MinDate: "минимально допустимая дата для ",
  ValidateNested: "вложенное свойство $property должно быть либо объектом, либо массивом",

}